// Panel painting. See drumpanel.h.
//
// The kit is an electronic drum kit seen from the player's seat, composited
// from the PNG layers in the bundle's Contents/Resources/img (generated by the
// ImageMagick scripts in gui/): hex pads for kick, snare and toms, round pads
// for hi-hat, crashes and ride. Every sprite load is null-checked — Canvas
// skips a null image — and a pad with no art falls back to its flat shape, so
// a missing resource directory degrades rather than crashes.

#include "drumpanel.h"

#include <cmath>
#include <cstdio>

namespace DRUMix
{

namespace
{
constexpr float kCornerRadius = 4.0f;
constexpr float kLabelFontSize = 12.0f;
constexpr float kPadFontSize = 11.0f;
// Baseline offset that centres text of kLabelFontSize on a rect's mid-line.
constexpr float kBaselineNudge = kLabelFontSize * 0.36f;

void noteName(int note, char *out, size_t outSize)
{
    static const char *kNames[12] = {"C",  "C#", "D",  "D#", "E",  "F",
                                     "F#", "G",  "G#", "A",  "A#", "B"};
    if (note < 0 || note > 127)
        std::snprintf(out, outSize, "unassigned");
    else
        std::snprintf(out, outSize, "%s%d (%d)", kNames[note % 12], note / 12 - 1, note);
}

// The same name without the MIDI number, for the narrow rack column.
void noteNameShort(int note, char *out, size_t outSize)
{
    static const char *kNames[12] = {"C",  "C#", "D",  "D#", "E",  "F",
                                     "F#", "G",  "G#", "A",  "A#", "B"};
    if (note < 0 || note > 127)
        std::snprintf(out, outSize, "\u2014");
    else
        std::snprintf(out, outSize, "%s%d", kNames[note % 12], note / 12 - 1);
}

cairo_surface_t *padSprite(ImageCache &images, int pad, const char *state)
{
    char name[64];
    std::snprintf(name, sizeof(name), "pad_%s_%s", geo::kPads[pad].sprite, state);
    return images.get(name);
}

// Flat fallback for a pad whose sprite failed to load: the shape in the two
// body colours, so the kit is still usable without its art.
void drawFlatPad(Canvas &c, const geo::PadSpec &pad)
{
    const float cx = static_cast<float>(pad.x);
    const float cy = static_cast<float>(pad.y);
    const float r = static_cast<float>(pad.r);

    if (!pad.hex) {
        c.setColor(geo::kPadBody);
        c.fillEllipse(cx, cy, r, r);
        c.setColor(geo::kPadRim);
        c.setPenSize(1.5f);
        c.strokeEllipse(cx, cy, r, r);
        return;
    }

    cairo_t *cr = c.cr();
    cairo_new_path(cr);
    for (int k = 0; k < 6; ++k) {
        const double a = M_PI / 180.0 * (60.0 * k);
        const double px = cx + r * std::cos(a);
        const double py = cy + r * std::sin(a);
        if (k == 0)
            cairo_move_to(cr, px, py);
        else
            cairo_line_to(cr, px, py);
    }
    cairo_close_path(cr);
    c.setColor(geo::kPadBody);
    cairo_fill_preserve(cr);
    c.setColor(geo::kPadRim);
    c.setPenSize(1.5f);
    cairo_stroke(cr);
}

void drawPads(Canvas &c, ImageCache &images, const PanelState &s)
{
    for (int i = 0; i < geo::kPadCount; ++i) {
        const geo::PadSpec &p = geo::kPads[i];
        // Every sprite carries the same transparent margin around its shape,
        // so all four layers of a pad register on one origin.
        const float side = static_cast<float>(2 * (p.r + geo::kPadMargin));
        const float ox = static_cast<float>(p.x) - side * 0.5f;
        const float oy = static_cast<float>(p.y) - side * 0.5f;

        if (cairo_surface_t *base = padSprite(images, i, "base"))
            c.drawImageAt(base, ox, oy);
        else
            drawFlatPad(c, p);

        if (s.hitLevel[i] > 0.0f)
            c.drawImageAt(padSprite(images, i, "hit"), ox, oy, s.hitLevel[i]);

        if (i == s.selectedPad)
            c.drawImageAt(padSprite(images, i, "sel"), ox, oy);

        if (p.slot == s.armedSlot) {
            const float pulse = 0.55f + 0.45f * std::sin(static_cast<float>(s.pulsePhase) * 0.35f);
            c.drawImageAt(padSprite(images, i, "arm"), ox, oy, pulse);
        }

        c.setFont(Font::Body);
        c.setFontSize(kPadFontSize);
        c.setColor(i == s.selectedPad ? geo::kTextColor : geo::kDimColor);
        const float w = c.stringWidth(p.name);
        c.drawString(p.name, static_cast<float>(p.x) - w * 0.5f, static_cast<float>(p.y) + 4.0f);
    }
}

// The one button look, used by the strip, the rack rows and the rack footer.
// `lit` is the MIDI-learn state, which takes over the whole button.
void drawButton(Canvas &c, const Rect &r, const char *label, float fontSize, bool pressed, bool lit,
                bool enabled)
{
    c.setColor(lit ? geo::kArmColor : (pressed ? geo::kSeparator : geo::kPadBody),
               enabled ? 255 : 150);
    c.fillRoundRect(r, kCornerRadius);
    c.setColor(lit ? geo::kArmColor : geo::kPadRim);
    c.setPenSize(1.0f);
    c.strokeRoundRect(r, kCornerRadius);

    c.setFont(Font::Body);
    c.setFontSize(fontSize);
    c.setColor(enabled ? geo::kTextColor : geo::kDimColor, enabled ? 255 : 160);
    const float w = c.stringWidth(label);
    c.drawString(label, r.centerX() - w * 0.5f, r.centerY() + fontSize * 0.36f);
}

void drawStripButton(Canvas &c, const PanelState &s, int index, bool lit, bool enabled)
{
    drawButton(c, buttonRect(index), geo::kButtons[index].label, kLabelFontSize,
               s.pressedButton == index, lit, enabled);
}

void drawVolume(Canvas &c, const PanelState &s)
{
    const float trackX = static_cast<float>(geo::kVolumeTrackX);
    const float trackW = static_cast<float>(geo::kVolumeTrackW);
    const float cy = static_cast<float>(geo::kVolumeCenterY);
    const float trackH = static_cast<float>(geo::kVolumeTrackH);
    const Rect track(trackX, cy - trackH * 0.5f, trackW, trackH);
    const float filled = trackW * static_cast<float>(s.volume);

    c.setFont(Font::Body);
    c.setFontSize(kLabelFontSize);
    c.setColor(geo::kDimColor);
    c.drawString("Volume", static_cast<float>(geo::kVolumeCaptionX), cy + kBaselineNudge);

    c.setColor(geo::kPadBody);
    c.fillRoundRect(track, trackH * 0.5f);
    if (filled > 0.0f) {
        c.setColor(geo::kAccent);
        c.fillRoundRect(Rect(track.x, track.y, filled, trackH), trackH * 0.5f);
    }

    const float knobR = static_cast<float>(geo::kVolumeKnobR);
    c.setColor(geo::kTextColor);
    c.fillEllipse(trackX + filled, cy, knobR, knobR);

    char value[16];
    std::snprintf(value, sizeof(value), "%.2f", s.volume);
    c.drawString(value, static_cast<float>(geo::kVolumeValueX), cy + kBaselineNudge);
}

void drawStrip(Canvas &c, const PanelState &s)
{
    const geo::PadSpec &pad = geo::kPads[s.selectedPad];
    const bool learning = (s.armedSlot == pad.slot);

    c.setColor(geo::kStripBg);
    c.fillRect(Rect(0.0f, static_cast<float>(geo::kStripY), static_cast<float>(geo::kWinW),
                    static_cast<float>(geo::kStripH)));
    c.setColor(geo::kSeparator);
    c.setPenSize(1.0f);
    c.strokeLine(0.0f, static_cast<float>(geo::kStripY) + 0.5f, static_cast<float>(geo::kWinW),
                 static_cast<float>(geo::kStripY) + 0.5f);

    char text[512];
    const float baseline = static_cast<float>(geo::kLabelBaseline);

    c.setFont(Font::Body);
    c.setFontSize(kLabelFontSize);
    c.setColor(geo::kTextColor);
    std::snprintf(text, sizeof(text), "%s  (slot %d)", pad.name, pad.slot + 1);
    c.drawString(text, static_cast<float>(geo::kPadLabelX), baseline);

    std::snprintf(text, sizeof(text), "sample: %s",
                  s.sampleLoaded ? s.sampleName.c_str() : "(none)");
    c.setColor(s.sampleLoaded ? geo::kTextColor : geo::kDimColor);
    const float fileW = static_cast<float>(geo::kNoteLabelX - geo::kFileLabelX - 12);
    c.drawString(c.clipToWidth(text, fileW).c_str(), static_cast<float>(geo::kFileLabelX),
                 baseline);

    if (learning) {
        c.setColor(geo::kArmColor);
        std::snprintf(text, sizeof(text), "note: listening…");
    } else {
        c.setColor(geo::kDimColor);
        char name[32];
        noteName(s.note, name, sizeof(name));
        std::snprintf(text, sizeof(text), "note: %s", name);
    }
    c.drawString(text, static_cast<float>(geo::kNoteLabelX), baseline);

    drawStripButton(c, s, geo::kLoadButton, false, true);
    drawStripButton(c, s, geo::kClearButton, false, s.sampleLoaded);
    drawStripButton(c, s, geo::kLearnButton, learning, true);
    drawVolume(c, s);

    // The way out of the nine pads: the rack page reaches every slot.
    drawButton(c, expandButtonRect(), "Expand kit \u203A", kLabelFontSize,
               s.pressedButton == geo::kButtonCount, false, true);

    c.setFont(Font::Title);
    c.setFontSize(13.0f);
    c.setColor(geo::kTitleColor);
    c.drawString("DRUMix", static_cast<float>(geo::kTitleX),
                 static_cast<float>(geo::kTitleBaseline));
}

} // namespace

//------------------------------------------------------------------------
void drawPanel(Canvas &c, ImageCache &images, const PanelState &state)
{
    if (cairo_surface_t *background = images.get("background")) {
        c.drawImageAt(background, 0.0f, 0.0f);
    } else {
        c.setColor(geo::kBgTop);
        c.fillRect(c.bounds());
    }

    drawPads(c, images, state);
    drawStrip(c, state);
}

//------------------------------------------------------------------------
// The kit rack page
//------------------------------------------------------------------------
namespace
{
constexpr float kRackFontSize = 11.0f;
constexpr float kRackNudge = kRackFontSize * 0.36f;

void drawRackHeader(Canvas &c, const RackState &s)
{
    c.setFont(Font::Title);
    c.setFontSize(20.0f);
    c.setColor(geo::kTextColor);
    c.drawString("KIT RACK", static_cast<float>(geo::kRackTitleX),
                 static_cast<float>(geo::kRackTitleBaseline));

    char text[64];
    std::snprintf(text, sizeof(text), "%d of %d slots shown", s.slotCount, s.maxSlots);
    c.setFont(Font::Body);
    c.setFontSize(kRackFontSize);
    c.setColor(geo::kDimColor);
    c.drawString(text, static_cast<float>(geo::kRackCountX),
                 static_cast<float>(geo::kRackTitleBaseline));

    const Rect close = rackCloseBox();
    c.setColor(s.pressedControl == kRackClose ? geo::kTextColor : geo::kDimColor);
    c.setPenSize(2.0f);
    c.strokeLine(close.left(), close.top(), close.right(), close.bottom());
    c.strokeLine(close.left(), close.bottom(), close.right(), close.top());
    c.setPenSize(1.0f);

    c.setColor(geo::kSeparator);
    c.strokeLine(
        static_cast<float>(geo::kRackRowLeft), static_cast<float>(geo::kRackHeaderRule) + 0.5f,
        static_cast<float>(geo::kRackRowRight), static_cast<float>(geo::kRackHeaderRule) + 0.5f);
}

void drawRackVolume(Canvas &c, const Rect &row, double volume)
{
    const float trackX = static_cast<float>(geo::kRackVolX);
    const float trackW = static_cast<float>(geo::kRackVolW);
    const float trackH = static_cast<float>(geo::kRackVolTrackH);
    const float cy = row.centerY();
    const float filled = trackW * static_cast<float>(volume);

    c.setColor(geo::kPadBody);
    c.fillRoundRect(Rect(trackX, cy - trackH * 0.5f, trackW, trackH), trackH * 0.5f);
    if (filled > 0.0f) {
        c.setColor(geo::kAccent);
        c.fillRoundRect(Rect(trackX, cy - trackH * 0.5f, filled, trackH), trackH * 0.5f);
    }
    c.setColor(geo::kTextColor);
    const float knobR = static_cast<float>(geo::kRackVolKnobR);
    c.fillEllipse(trackX + filled, cy, knobR, knobR);

    char value[16];
    std::snprintf(value, sizeof(value), "%.2f", volume);
    c.setColor(geo::kDimColor);
    c.drawString(value, static_cast<float>(geo::kRackVolValueX), cy + kRackNudge);
}

void drawRackRow(Canvas &c, const RackState &s, int position, const RackRow &r)
{
    const Rect row = rackRowRect(position);

    // Zebra banding, then the trigger flash over it, so a pad firing is as
    // visible here as it is on the kit page.
    if ((r.slot & 1) != 0) {
        c.setColor(geo::kPadBody, 120);
        c.fillRect(row);
    }
    if (r.hitLevel > 0.0f) {
        // A tint alone reads as "this row is selected"; the bright underline is
        // what makes it read as a pulse.
        c.setColor(geo::kHitGlow, static_cast<int>(r.hitLevel * 34.0f));
        c.fillRect(row);
        c.setColor(geo::kHitGlow, static_cast<int>(r.hitLevel * 255.0f));
        c.fillRect(Rect(row.x, row.bottom() - 2.0f, row.w, 2.0f));
    }
    // The slot the kit page has selected, marked so the two pages agree.
    if (r.slot == s.selectedSlot) {
        c.setColor(geo::kAccent);
        c.fillRect(Rect(row.x, row.y + 3.0f, 3.0f, row.h - 6.0f));
    }

    c.setFont(Font::Body);
    c.setFontSize(kRackFontSize);
    const float baseline = row.centerY() + kRackNudge;

    char text[512];
    std::snprintf(text, sizeof(text), "%02d", r.slot + 1);
    c.setColor(geo::kDimColor);
    c.drawString(text, static_cast<float>(geo::kRackIndexX), baseline);

    if (r.name) {
        c.setColor(geo::kTextColor);
        std::snprintf(text, sizeof(text), "%s", r.name);
    } else {
        c.setColor(geo::kDimColor);
        std::snprintf(text, sizeof(text), "Slot %d", r.slot + 1);
    }
    c.drawString(c.clipToWidth(text, static_cast<float>(geo::kRackNameW)).c_str(),
                 static_cast<float>(geo::kRackNameX), baseline);

    c.setColor(r.sampleLoaded ? geo::kTextColor : geo::kDimColor);
    const char *file = r.sampleLoaded ? r.sampleName.c_str() : "(empty)";
    c.drawString(c.clipToWidth(file, static_cast<float>(geo::kRackFileW)).c_str(),
                 static_cast<float>(geo::kRackFileX), baseline);

    drawRackVolume(c, row, r.volume);

    if (r.armed) {
        const float pulse = 0.55f + 0.45f * std::sin(static_cast<float>(s.pulsePhase) * 0.35f);
        c.setColor(geo::kArmColor, static_cast<int>(pulse * 255.0f));
        std::snprintf(text, sizeof(text), "listening\u2026");
    } else {
        c.setColor(r.note >= 0 ? geo::kTextColor : geo::kDimColor);
        noteNameShort(r.note, text, sizeof(text));
    }
    c.drawString(c.clipToWidth(text, static_cast<float>(geo::kRackNoteW)).c_str(),
                 static_cast<float>(geo::kRackNoteX), baseline);

    const bool held = (s.pressedRow == r.slot);
    for (int b = 0; b < geo::kRackButtonCount; ++b) {
        const bool enabled = (b != geo::kRackClearButton) || r.sampleLoaded;
        drawButton(c, rackButtonRect(position, b), geo::kRackButtons[b].label, kRackFontSize,
                   held && s.pressedButton == b, b == geo::kRackLearnButton && r.armed, enabled);
    }
}

// Scroll indicator: only when the list is longer than the window.
void drawRackScrollbar(Canvas &c, const RackState &s)
{
    if (s.slotCount <= geo::kRackVisibleRows)
        return;

    const float top = static_cast<float>(geo::kRackRowsY);
    const float height = static_cast<float>(geo::kRackVisibleRows * geo::kRackRowH);
    const float w = static_cast<float>(geo::kRackScrollW);
    const Rect track(static_cast<float>(geo::kRackScrollX), top, w, height);
    c.setColor(geo::kPadBody);
    c.fillRoundRect(track, w * 0.5f);

    const float visible =
        static_cast<float>(geo::kRackVisibleRows) / static_cast<float>(s.slotCount);
    const float thumbH = height * visible < 24.0f ? 24.0f : height * visible;
    const int maxFirst = s.slotCount - geo::kRackVisibleRows;
    const float progress =
        maxFirst > 0 ? static_cast<float>(s.firstRow) / static_cast<float>(maxFirst) : 0.0f;
    c.setColor(geo::kSeparator);
    c.fillRoundRect(Rect(track.x, top + (height - thumbH) * progress, w, thumbH), w * 0.5f);
}

void drawRackFooter(Canvas &c, const RackState &s)
{
    c.setColor(geo::kSeparator);
    c.setPenSize(1.0f);
    c.strokeLine(
        static_cast<float>(geo::kRackRowLeft), static_cast<float>(geo::kRackFooterRule) + 0.5f,
        static_cast<float>(geo::kRackRowRight), static_cast<float>(geo::kRackFooterRule) + 0.5f);

    drawButton(c, rackAddRect(), "+ Add slot", kLabelFontSize, s.pressedControl == kRackAdd, false,
               s.slotCount < s.maxSlots);
    drawButton(c, rackRemoveRect(), "\u2212 Remove slot", kLabelFontSize,
               s.pressedControl == kRackRemove, false, s.slotCount > 1);

    // Removing a row only hides the slot: its sample, note and volume are kept
    // and still play. Say so, because the button reads destructive.
    c.setFont(Font::Body);
    c.setFontSize(kRackFontSize);
    c.setColor(geo::kDimColor);
    c.drawString("Hidden slots keep their sample and keep playing \u00b7 wheel scrolls",
                 static_cast<float>(geo::kRackHintX),
                 static_cast<float>(geo::kRackFooterY + geo::kRackFooterH / 2) + kRackNudge);
}
} // namespace

//------------------------------------------------------------------------
void drawRack(Canvas &c, const RackState &state)
{
    c.setColor(geo::kStripBg);
    c.fillRect(c.bounds());
    c.setColor(geo::kSeparator);
    c.setPenSize(1.0f);
    c.strokeRoundRect(c.bounds().inset(8.0f), 10.0f);

    drawRackHeader(c, state);

    const int shown = static_cast<int>(state.rows.size()) < geo::kRackVisibleRows
                          ? static_cast<int>(state.rows.size())
                          : geo::kRackVisibleRows;
    for (int i = 0; i < shown; ++i)
        drawRackRow(c, state, i, state.rows[static_cast<size_t>(i)]);

    drawRackScrollbar(c, state);
    drawRackFooter(c, state);
}

//------------------------------------------------------------------------
double rackVolumeForX(float x)
{
    const double norm =
        (x - static_cast<float>(geo::kRackVolX)) / static_cast<double>(geo::kRackVolW);
    return norm < 0.0 ? 0.0 : (norm > 1.0 ? 1.0 : norm);
}

//------------------------------------------------------------------------
double volumeForX(float x)
{
    const double norm =
        (x - static_cast<float>(geo::kVolumeTrackX)) / static_cast<double>(geo::kVolumeTrackW);
    return norm < 0.0 ? 0.0 : (norm > 1.0 ? 1.0 : norm);
}

} // namespace DRUMix
