// Panel painting. See drumpanel.h.
//
// The kit is an electronic drum kit seen from the player's seat, composited
// from the PNG layers in the bundle's Contents/Resources/img (generated by the
// ImageMagick scripts in gui/): hex pads for kick, snare and toms, round pads
// for hi-hat, crashes and ride. Every sprite load is null-checked — Canvas
// skips a null image — and a pad with no art falls back to its flat shape, so
// a missing resource directory degrades rather than crashes.

#include "drumpanel.h"

#include <cmath>
#include <cstdio>

namespace DRUMix
{

namespace
{
constexpr float kCornerRadius = 4.0f;
constexpr float kLabelFontSize = 12.0f;
constexpr float kPadFontSize = 11.0f;
// Baseline offset that centres text of kLabelFontSize on a rect's mid-line.
constexpr float kBaselineNudge = kLabelFontSize * 0.36f;

void noteName(int note, char *out, size_t outSize)
{
    static const char *kNames[12] = {"C",  "C#", "D",  "D#", "E",  "F",
                                     "F#", "G",  "G#", "A",  "A#", "B"};
    if (note < 0 || note > 127)
        std::snprintf(out, outSize, "unassigned");
    else
        std::snprintf(out, outSize, "%s%d (%d)", kNames[note % 12], note / 12 - 1, note);
}

cairo_surface_t *padSprite(ImageCache &images, int pad, const char *state)
{
    char name[64];
    std::snprintf(name, sizeof(name), "pad_%s_%s", geo::kPads[pad].sprite, state);
    return images.get(name);
}

// Flat fallback for a pad whose sprite failed to load: the shape in the two
// body colours, so the kit is still usable without its art.
void drawFlatPad(Canvas &c, const geo::PadSpec &pad)
{
    const float cx = static_cast<float>(pad.x);
    const float cy = static_cast<float>(pad.y);
    const float r = static_cast<float>(pad.r);

    if (!pad.hex) {
        c.setColor(geo::kPadBody);
        c.fillEllipse(cx, cy, r, r);
        c.setColor(geo::kPadRim);
        c.setPenSize(1.5f);
        c.strokeEllipse(cx, cy, r, r);
        return;
    }

    cairo_t *cr = c.cr();
    cairo_new_path(cr);
    for (int k = 0; k < 6; ++k) {
        const double a = M_PI / 180.0 * (60.0 * k);
        const double px = cx + r * std::cos(a);
        const double py = cy + r * std::sin(a);
        if (k == 0)
            cairo_move_to(cr, px, py);
        else
            cairo_line_to(cr, px, py);
    }
    cairo_close_path(cr);
    c.setColor(geo::kPadBody);
    cairo_fill_preserve(cr);
    c.setColor(geo::kPadRim);
    c.setPenSize(1.5f);
    cairo_stroke(cr);
}

void drawPads(Canvas &c, ImageCache &images, const PanelState &s)
{
    for (int i = 0; i < geo::kPadCount; ++i) {
        const geo::PadSpec &p = geo::kPads[i];
        // Every sprite carries the same transparent margin around its shape,
        // so all four layers of a pad register on one origin.
        const float side = static_cast<float>(2 * (p.r + geo::kPadMargin));
        const float ox = static_cast<float>(p.x) - side * 0.5f;
        const float oy = static_cast<float>(p.y) - side * 0.5f;

        if (cairo_surface_t *base = padSprite(images, i, "base"))
            c.drawImageAt(base, ox, oy);
        else
            drawFlatPad(c, p);

        if (s.hitLevel[i] > 0.0f)
            c.drawImageAt(padSprite(images, i, "hit"), ox, oy, s.hitLevel[i]);

        if (i == s.selectedPad)
            c.drawImageAt(padSprite(images, i, "sel"), ox, oy);

        if (p.slot == s.armedSlot) {
            const float pulse = 0.55f + 0.45f * std::sin(static_cast<float>(s.pulsePhase) * 0.35f);
            c.drawImageAt(padSprite(images, i, "arm"), ox, oy, pulse);
        }

        c.setFont(Font::Body);
        c.setFontSize(kPadFontSize);
        c.setColor(i == s.selectedPad ? geo::kTextColor : geo::kDimColor);
        const float w = c.stringWidth(p.name);
        c.drawString(p.name, static_cast<float>(p.x) - w * 0.5f, static_cast<float>(p.y) + 4.0f);
    }
}

void drawButton(Canvas &c, const PanelState &s, int index, bool lit, bool enabled)
{
    const geo::ButtonSpec &spec = geo::kButtons[index];
    const Rect r = buttonRect(index);
    const bool pressed = (s.pressedButton == index);

    c.setColor(lit ? geo::kArmColor : (pressed ? geo::kSeparator : geo::kPadBody),
               enabled ? 255 : 150);
    c.fillRoundRect(r, kCornerRadius);
    c.setColor(lit ? geo::kArmColor : geo::kPadRim);
    c.setPenSize(1.0f);
    c.strokeRoundRect(r, kCornerRadius);

    c.setFont(Font::Body);
    c.setFontSize(kLabelFontSize);
    c.setColor(enabled ? geo::kTextColor : geo::kDimColor, enabled ? 255 : 160);
    const float w = c.stringWidth(spec.label);
    c.drawString(spec.label, r.centerX() - w * 0.5f, r.centerY() + kBaselineNudge);
}

void drawVolume(Canvas &c, const PanelState &s)
{
    const float trackX = static_cast<float>(geo::kVolumeTrackX);
    const float trackW = static_cast<float>(geo::kVolumeTrackW);
    const float cy = static_cast<float>(geo::kVolumeCenterY);
    const float trackH = static_cast<float>(geo::kVolumeTrackH);
    const Rect track(trackX, cy - trackH * 0.5f, trackW, trackH);
    const float filled = trackW * static_cast<float>(s.volume);

    c.setFont(Font::Body);
    c.setFontSize(kLabelFontSize);
    c.setColor(geo::kDimColor);
    c.drawString("Volume", static_cast<float>(geo::kVolumeCaptionX), cy + kBaselineNudge);

    c.setColor(geo::kPadBody);
    c.fillRoundRect(track, trackH * 0.5f);
    if (filled > 0.0f) {
        c.setColor(geo::kAccent);
        c.fillRoundRect(Rect(track.x, track.y, filled, trackH), trackH * 0.5f);
    }

    const float knobR = static_cast<float>(geo::kVolumeKnobR);
    c.setColor(geo::kTextColor);
    c.fillEllipse(trackX + filled, cy, knobR, knobR);

    char value[16];
    std::snprintf(value, sizeof(value), "%.2f", s.volume);
    c.drawString(value, static_cast<float>(geo::kVolumeValueX), cy + kBaselineNudge);
}

void drawStrip(Canvas &c, const PanelState &s)
{
    const geo::PadSpec &pad = geo::kPads[s.selectedPad];
    const bool learning = (s.armedSlot == pad.slot);

    c.setColor(geo::kStripBg);
    c.fillRect(Rect(0.0f, static_cast<float>(geo::kStripY), static_cast<float>(geo::kWinW),
                    static_cast<float>(geo::kStripH)));
    c.setColor(geo::kSeparator);
    c.setPenSize(1.0f);
    c.strokeLine(0.0f, static_cast<float>(geo::kStripY) + 0.5f, static_cast<float>(geo::kWinW),
                 static_cast<float>(geo::kStripY) + 0.5f);

    char text[512];
    const float baseline = static_cast<float>(geo::kLabelBaseline);

    c.setFont(Font::Body);
    c.setFontSize(kLabelFontSize);
    c.setColor(geo::kTextColor);
    std::snprintf(text, sizeof(text), "%s  (slot %d)", pad.name, pad.slot + 1);
    c.drawString(text, static_cast<float>(geo::kPadLabelX), baseline);

    std::snprintf(text, sizeof(text), "sample: %s",
                  s.sampleLoaded ? s.sampleName.c_str() : "(none)");
    c.setColor(s.sampleLoaded ? geo::kTextColor : geo::kDimColor);
    const float fileW = static_cast<float>(geo::kNoteLabelX - geo::kFileLabelX - 12);
    c.drawString(c.clipToWidth(text, fileW).c_str(), static_cast<float>(geo::kFileLabelX),
                 baseline);

    if (learning) {
        c.setColor(geo::kArmColor);
        std::snprintf(text, sizeof(text), "note: listening…");
    } else {
        c.setColor(geo::kDimColor);
        char name[32];
        noteName(s.note, name, sizeof(name));
        std::snprintf(text, sizeof(text), "note: %s", name);
    }
    c.drawString(text, static_cast<float>(geo::kNoteLabelX), baseline);

    drawButton(c, s, geo::kLoadButton, false, true);
    drawButton(c, s, geo::kClearButton, false, s.sampleLoaded);
    drawButton(c, s, geo::kLearnButton, learning, true);
    drawVolume(c, s);

    c.setFont(Font::Title);
    c.setFontSize(13.0f);
    c.setColor(geo::kSeparator);
    c.drawString("DRUMix", static_cast<float>(geo::kTitleX),
                 static_cast<float>(geo::kTitleBaseline));
}

} // namespace

//------------------------------------------------------------------------
void drawPanel(Canvas &c, ImageCache &images, const PanelState &state)
{
    if (cairo_surface_t *background = images.get("background")) {
        c.drawImageAt(background, 0.0f, 0.0f);
    } else {
        c.setColor(geo::kBgTop);
        c.fillRect(c.bounds());
    }

    drawPads(c, images, state);
    drawStrip(c, state);
}

//------------------------------------------------------------------------
double volumeForX(float x)
{
    const double norm =
        (x - static_cast<float>(geo::kVolumeTrackX)) / static_cast<double>(geo::kVolumeTrackW);
    return norm < 0.0 ? 0.0 : (norm > 1.0 ? 1.0 : norm);
}

} // namespace DRUMix
